### ISSUE TITLE
Add a method to track a person's eyes in live video stream.

### ISSUE THREAD

**Issue by ayushanand308** [mrsparkle-70/Emotion-detection-using-JS#55]
We can add a JS method that track's the position of a person's eyes using face-api.

**Comment by ayushanand308** [comment]
@mrsparkle-70 Please assign me this issue under JWOC.

**Comment by mrsparkle-70** [comment]
Ok u start

**Comment by ayushanand308** [comment]
@mrsparkle-70 On it.

**Comment by mrsparkle-70** [comment]
Any progress ?

**Comment by ayushanand308** [comment]
@mrsparkle-70 

I am getting the following error 

eyes.js:46 TypeError: Cannot read properties of null (reading 'getContext')
    at drawDot (eyes.js:61:22)
    at eyes.js:40:9
    at e.<anonymous> (face-api.min.js:1:554678)
    at face-api.min.js:1:1935
    at Object.next (face-api.min.js:1:2040)
    at n (face-api.min.js:1:811)
    
    
    
    I have console logged and face-api is loading correctly, it is also calculating the positions of pupils correctly but getting this error. Any inputs?

**Comment by ayushanand308** [comment]
@mrsparkle-70  You can assign this issue to someone else as I am busy with my semester exams. :-)

**Comment by Prateek556** [comment]
I would like to work on this issue under JWOC

**Comment by mrsparkle-70** [comment]
Sure you can start
I will assign

**Comment by Prateek556** [comment]
ok please assign me this issue.

**Comment by mrsparkle-70** [comment]
Any progress ?
